services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://task_user:securepassword@postgres:5432/task_db"
      JWT_SECRET: "your_jwt_secret"
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "dev"]

volumes:
  postgres_data: